version: '3'
services:
  mongo:
    image: mongo
    expose:
      - 27017
  app:
    build: .
    volumes:
      - ./api/:/usr/src/app/api
      - ./public/:/usr/src/app/public
      - ./routes/:/usr/src/app/routes
      - ./views/:/usr/src/app/views
    depends_on:
      - mongo
    ports:
      - 3000:3000
