entryPoints:
  web:
    address: ':80'
  web-secure:
    address: ':443'

certificatesResolvers:
  educatopiaResolver:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: letsencrypt@ad-si.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

log:
  level: WARN
  filePath: traefik.log

accessLog:
  # Lines to keep in memory before writing to log file
  bufferingSize: 32
  filePath: traefik_access.log
  format: json
  fields:
    defaultMode: drop
    names:
      StartUTC: keep
      Duration: keep
      ClientAddr: keep
      RequestMethod: keep
      RequestProtocol: keep
      RequestAddr: keep
      RequestPath: keep
      RequestContentSize: keep
      DownstreamStatus: keep
      DownstreamContentSize: keep
      RetryAttempts: keep

    headers:
      defaultMode: drop
      names:
        Referer: keep
        User-Agent: keep

providers:
  file:
    filename: /root/educatopia/traefik_routing.yaml
