entryPoints:
  web:
    address: ':80'
  web-secure:
    address: ':443'

certificatesResolvers:
  educatopiaResolver:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: letsencrypt@ad-si.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG
  filePath: traefik.log
  format: json

accessLog:
  filePath: traefik_access.log
  format: json

providers:
  file:
    filename: /root/educatopia/traefik_routing.yaml
